const ACTION_TYPES = {
  LOGIN_REQUEST_PENDING: "LOGIN_REQUEST_PENDING",
  LOGIN_REQUEST: "LOGIN_REQUEST",
  CLIENT_REQUEST: "CLIENT_REQUEST",
  CLIENT_REQUEST_PENDING: "CLIENT_REQUEST_PENDING",

  INTAKE_SURVEY_SAVE_PENDING: "INTAKE_SURVEY_SAVE_PENDING",

  API_REQUEST_FAILED: "API_REQUEST_FAILED"
};

export default ACTION_TYPES;
