const ACTION_TYPES = {
  LOGIN_REQUEST_PENDING: "LOGIN_REQUEST_PENDING",
  LOGIN_REQUEST: "LOGIN_REQUEST",
  CLIENT_REQUEST: "CLIENT_REQUEST",
  CLIENT_REQUEST_PENDING: "CLIENT_REQUEST_PENDING",
  LOGOUT: "LOGOUT",
  SHELTER_REQUEST: "SHELTER_REQUEST",
  SHELTER_REQUEST_PENDING: "SHELTER_REQUEST_PENDING",
  CLIENT_SPDAT_REQUEST: "CLIENT_SPDAT_REQUEST",

  INTAKE_SURVEY_SAVE_PENDING: "INTAKE_SURVEY_SAVE_PENDING",

  INTAKE_POSTED: "INTAKE_POSTED",
  NEED_CREATED: "NEED_CREATED",

  API_REQUEST_FAILED: "API_REQUEST_FAILED"
};

export default ACTION_TYPES;
